fieldLayouts:
  1e000c74-8814-45c7-9577-2e78a89f1015:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6d716d1c-c835-401a-affa-34ca4a00419c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a92a63ae-ec46-4551-9c48-253b99eb253f # video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9082cda4-99c0-478e-a986-128b0d171953
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 810a3b9c-0fe2-4aa5-a862-519ee8a3a61f
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: e608cd8d-8672-4dd1-8c1d-a1b2abfed433 # videos
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
