fieldLayouts:
  a3ba13fa-b184-4c1a-b41b-d12a26d43440:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 53abe8c6-b796-4446-bfa4-0f396a3373f5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 58439dea-1f21-4e65-85b9-b2bf2ff2f200
            userCondition: null
          -
            elementCondition: null
            fieldUid: 2a69dda1-ce75-46be-a52d-e23ef35bd222 # Sticker image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80f3bdb2-756b-4ae6-b870-f163edfaf512
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e9371a2a-fd6e-4328-8548-3afb9d169679 # Sticker Shape
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ff7cfb8-158f-40d4-a0c1-e593410f8ebb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa884e65-7b76-453e-aba1-93ac4c48cb4d # Sticker Fill
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20a9ef0f-796b-4739-9a11-2ed767dc6468
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c54b5ded-0ff8-4cc5-9fd5-b9b7ebb46d52 # Sticker Colorway
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a699122-5847-463b-95af-0e9fddd4ccc0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 450a0d36-bbf3-456d-9ea1-afe0d0e73d4e # Sticker Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd244210-e650-4720-ba5e-2010be3e92bb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3c733d8b-1dae-47de-a178-ff384cd16e74
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 6b375cf4-73fe-4131-917b-46186b6379cc # presetStickers
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
