fieldLayouts:
  dd309334-8fe7-4c27-b0ff-a538f7be97c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 788760e0-3cb4-4230-afd2-5152371ef3d8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: fb25135d-34e3-440e-ada3-b155a1ee4b66
            userCondition: null
          -
            elementCondition: null
            fieldUid: 3ddb6261-c728-4f07-a386-3db0e589abb9 # Name Sticker
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09665740-e332-4e04-8aa8-4345c71b6580
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d4082b4-66b4-45ad-a5e4-9cba64245fce # Settings Sticker
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fac24973-4643-4a09-b761-fdf480f7259d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 08276a0c-1897-4e58-8100-fb5d44b00545
            userCondition: null
          -
            elementCondition: null
            fieldUid: e9371a2a-fd6e-4328-8548-3afb9d169679 # Sticker Shape
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bdf35c3-4e80-4744-8cba-c4c862a99d16
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c54b5ded-0ff8-4cc5-9fd5-b9b7ebb46d52 # Sticker Colorway
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4833361-e368-43d0-a63b-27dc9cf0ecb2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa884e65-7b76-453e-aba1-93ac4c48cb4d # Sticker Fill
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f598cc0e-8342-4920-85e4-be90c13b2828
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 78b8f78a-3461-4698-bf81-1c1cf1fb1123
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 69714cb8-a137-4c05-bd74-e4b148008185 # stickers
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
