fieldLayouts:
  bf350654-c641-4220-b934-fe46e60273e8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 33859c7c-9d18-4211-93d5-1f5a0b2aa33c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c6661952-992d-4f79-9f42-969c38cad38b # Question number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: badb877f-a869-4677-bad5-3faf56b54b6e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1da56d22-2bfa-4cd8-a4ae-d1e74b88970e # Question content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcd21b02-3177-4c0a-8369-5d775942c8ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55ab1228-dcf1-4be4-a70e-7cc9d4bd479e # Question answers
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0a76066-840c-4e4a-b638-47c26cc4a6ac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a1c2bcf-a02b-4d6d-a69c-3813e994542e # Question type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bfe06ca-a0ef-4316-839f-2336aacca772
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7e7fdf0e-27b3-4641-96a3-11598fdd4c9d
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: b4a4bcbb-81be-4b5c-ba1f-021a63e23601 # questions
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
