columnSuffix: gzhonefc
contentColumnType: text
fieldGroup: 960ed2f7-5864-4beb-a32d-9fd7d64d2a7a # Sticker Meta
handle: nameSticker
instructions: null
name: 'Name Sticker'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
