columnSuffix: elrrlmcf
contentColumnType: text
fieldGroup: 92324d39-754a-4693-911f-fd24b88c1275 # Question info
handle: questionContent
instructions: null
name: 'Question content'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
